name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run TypeScript type check
      run: npm run build
      
    - name: Run linting (if available)
      run: |
        if npm run lint --if-present; then
          echo "Linting completed"
        else
          echo "No linting script found, skipping"
        fi
      
    - name: Run tests (if available)
      run: |
        if npm test --if-present; then
          echo "Tests completed"
        else
          echo "No test script found, skipping"
        fi

  validate-config:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Validate MCP server configuration
      run: |
        echo "Validating MCP server structure..."
        if [ -f "dist/index.js" ]; then
          echo "✅ MCP server build successful"
        else
          echo "❌ MCP server build failed"
          exit 1
        fi
